### ISSUE TITLE
Improving project health by setting up CI and other fun stuff

### ISSUE THREAD

**Issue by krishnagopinath** [Matterwiki/Matterwiki#105]
The general idea is that we'd need to configure these correctly:

- [ ] Good CI setup
- [ ] Code coverage checker
- [ ] Dependency updates (Greenkeeper)
- [ ] Deploy to Heroku/Firebase button
- [ ] Maintaining an updated Docker image
- [ ] Setting up a Demo URL
