### ISSUE TITLE
Refactor React components and Reduce boilerplate

### ISSUE THREAD

**Issue by krishnagopinath** [Matterwiki/Matterwiki#90]
- [ ] [Presentation and Stateful](https://medium.com/@dan_abramov/smart-and-dumb-components-7ca2f9a7c7d0)
- [x] Throw all fetch calls into a utils file. Maybe use axios or something?
- [x] Rename files from jsx to js
- [x] Names. The variable names inside WikiEditor (maybe in other areas of the app) are misleading. We could standardize the names so that they convey the intended meaning
- [x] [Restructure]( https://jaysoo.ca/2016/02/28/organizing-redux-application/) - [See this too](https://gist.github.com/ryanflorence/daafb1e3cb8ad740b346) 
- [x] Move everything to ~~react-bootstrap~~ react-strap
- [ ] Flow or PropTypes for correct typing and safety
- [x] Add [public class initializers](https://egghead.io/lessons/javascript-public-class-fields-with-react-components) to reduce boilerplate. 
- [x] switch to React Router v4 
- [ ] ~~Make a f-as-child kinda wrapper for API - https://medium.com/merrickchristensen/function-as-child-components-5f3920a9ace9~~
